import {
  SENTRY_DSN,
  SENTRY_URL,
  SENTRY_ORG,
  SENTRY_PROJECT,
  SENTRY_AUTH_TOKEN,
  FIREBASE_API_KEY,
  FIREBASE_APP_ID,
  FIREBASE_PROJECT_ID,
  REVENUECAT_IOS_KEY,
  REVENUECAT_ANDROID_KEY,
  // @feature:applovin-max:start [disabled]
  // APPLOVIN_SDK_KEY,
  // APPLOVIN_BANNER_AD_UNIT_IOS,
  // APPLOVIN_BANNER_AD_UNIT_ANDROID,
  // APPLOVIN_INTERSTITIAL_AD_UNIT_IOS,
  // APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID,
  // APPLOVIN_REWARDED_AD_UNIT_IOS,
  // APPLOVIN_REWARDED_AD_UNIT_ANDROID,
  // APPLOVIN_APP_OPEN_AD_UNIT_IOS,
  // APPLOVIN_APP_OPEN_AD_UNIT_ANDROID,
  // @feature:applovin-max:end
  // @feature:admob:start
  ADMOB_APP_ID_IOS,
  ADMOB_APP_ID_ANDROID,
  ADMOB_BANNER_AD_UNIT_IOS,
  ADMOB_BANNER_AD_UNIT_ANDROID,
  ADMOB_INTERSTITIAL_AD_UNIT_IOS,
  ADMOB_INTERSTITIAL_AD_UNIT_ANDROID,
  ADMOB_REWARDED_AD_UNIT_IOS,
  ADMOB_REWARDED_AD_UNIT_ANDROID,
  ADMOB_APP_OPEN_AD_UNIT_IOS,
  ADMOB_APP_OPEN_AD_UNIT_ANDROID,
  ADMOB_NATIVE_AD_UNIT_IOS,
  ADMOB_NATIVE_AD_UNIT_ANDROID,
  // @feature:admob:end
  FACEBOOK_APP_ID,
  FACEBOOK_CLIENT_TOKEN,
  // @feature:adjust:start
  ADJUST_APP_TOKEN_ANDROID,
  ADJUST_APP_TOKEN_IOS,
  // @feature:adjust:end
  USER_CENTRIC,
  USER_CENTRIC_RULESET_ID,
  USER_CENTRIC_SETTINGS_ID,
  USER_CENTRIC_IDENTITY_MODE,
} from '@env'

export type Env = {
  FACEBOOK_DISPLAY_NAME: any
  SENTRY_DSN: string
  SENTRY_URL: string
  SENTRY_ORG: string
  SENTRY_PROJECT: string
  SENTRY_AUTH_TOKEN: string
  FIREBASE_API_KEY: string
  FIREBASE_APP_ID: string
  FIREBASE_PROJECT_ID: string
  REVENUECAT_IOS_KEY: string
  REVENUECAT_ANDROID_KEY: string
  // @feature:applovin-max:start [disabled]
  // APPLOVIN_SDK_KEY: string
  // APPLOVIN_BANNER_AD_UNIT_IOS: string
  // APPLOVIN_BANNER_AD_UNIT_ANDROID: string
  // APPLOVIN_INTERSTITIAL_AD_UNIT_IOS: string
  // APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID: string
  // APPLOVIN_REWARDED_AD_UNIT_IOS: string
  // APPLOVIN_REWARDED_AD_UNIT_ANDROID: string
  // APPLOVIN_APP_OPEN_AD_UNIT_IOS: string
  // APPLOVIN_APP_OPEN_AD_UNIT_ANDROID: string
  // @feature:applovin-max:end
  // @feature:admob:start
  ADMOB_APP_ID_IOS: string
  ADMOB_APP_ID_ANDROID: string
  ADMOB_BANNER_AD_UNIT_IOS: string
  ADMOB_BANNER_AD_UNIT_ANDROID: string
  ADMOB_INTERSTITIAL_AD_UNIT_IOS: string
  ADMOB_INTERSTITIAL_AD_UNIT_ANDROID: string
  ADMOB_REWARDED_AD_UNIT_IOS: string
  ADMOB_REWARDED_AD_UNIT_ANDROID: string
  ADMOB_APP_OPEN_AD_UNIT_IOS: string
  ADMOB_APP_OPEN_AD_UNIT_ANDROID: string
  ADMOB_NATIVE_AD_UNIT_IOS: string
  ADMOB_NATIVE_AD_UNIT_ANDROID: string
  // @feature:admob:end
  FACEBOOK_APP_ID: string
  FACEBOOK_CLIENT_TOKEN: string
  // @feature:adjust:start
  ADJUST_APP_TOKEN_ANDROID: string
  ADJUST_APP_TOKEN_IOS: string
  // @feature:adjust:end
  USER_CENTRIC: string
  USER_CENTRIC_RULESET_ID: string
  USER_CENTRIC_SETTINGS_ID: string
  USER_CENTRIC_IDENTITY_MODE: string
}

const env: Env = {
  FACEBOOK_DISPLAY_NAME: '',
  SENTRY_DSN: SENTRY_DSN ?? '',
  SENTRY_URL: SENTRY_URL ?? 'https://sentry.io/',
  SENTRY_ORG: SENTRY_ORG ?? '',
  SENTRY_PROJECT: SENTRY_PROJECT ?? '',
  SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN ?? '',
  FIREBASE_API_KEY: FIREBASE_API_KEY ?? '',
  FIREBASE_APP_ID: FIREBASE_APP_ID ?? '',
  FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID ?? '',
  REVENUECAT_IOS_KEY: REVENUECAT_IOS_KEY ?? '',
  REVENUECAT_ANDROID_KEY: REVENUECAT_ANDROID_KEY ?? '',
  // @feature:applovin-max:start [disabled]
  // APPLOVIN_SDK_KEY: APPLOVIN_SDK_KEY ?? '',
  // APPLOVIN_BANNER_AD_UNIT_IOS: APPLOVIN_BANNER_AD_UNIT_IOS ?? '',
  // APPLOVIN_BANNER_AD_UNIT_ANDROID: APPLOVIN_BANNER_AD_UNIT_ANDROID ?? '',
  // APPLOVIN_INTERSTITIAL_AD_UNIT_IOS: APPLOVIN_INTERSTITIAL_AD_UNIT_IOS ?? '',
  // APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID: APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID ?? '',
  // APPLOVIN_REWARDED_AD_UNIT_IOS: APPLOVIN_REWARDED_AD_UNIT_IOS ?? '',
  // APPLOVIN_REWARDED_AD_UNIT_ANDROID: APPLOVIN_REWARDED_AD_UNIT_ANDROID ?? '',
  // APPLOVIN_APP_OPEN_AD_UNIT_IOS: APPLOVIN_APP_OPEN_AD_UNIT_IOS ?? '',
  // APPLOVIN_APP_OPEN_AD_UNIT_ANDROID: APPLOVIN_APP_OPEN_AD_UNIT_ANDROID ?? '',
  // @feature:applovin-max:end
  // @feature:admob:start
  ADMOB_APP_ID_IOS: ADMOB_APP_ID_IOS ?? '',
  ADMOB_APP_ID_ANDROID: ADMOB_APP_ID_ANDROID ?? '',
  ADMOB_BANNER_AD_UNIT_IOS: ADMOB_BANNER_AD_UNIT_IOS ?? '',
  ADMOB_BANNER_AD_UNIT_ANDROID: ADMOB_BANNER_AD_UNIT_ANDROID ?? '',
  ADMOB_INTERSTITIAL_AD_UNIT_IOS: ADMOB_INTERSTITIAL_AD_UNIT_IOS ?? '',
  ADMOB_INTERSTITIAL_AD_UNIT_ANDROID: ADMOB_INTERSTITIAL_AD_UNIT_ANDROID ?? '',
  ADMOB_REWARDED_AD_UNIT_IOS: ADMOB_REWARDED_AD_UNIT_IOS ?? '',
  ADMOB_REWARDED_AD_UNIT_ANDROID: ADMOB_REWARDED_AD_UNIT_ANDROID ?? '',
  ADMOB_APP_OPEN_AD_UNIT_IOS: ADMOB_APP_OPEN_AD_UNIT_IOS ?? '',
  ADMOB_APP_OPEN_AD_UNIT_ANDROID: ADMOB_APP_OPEN_AD_UNIT_ANDROID ?? '',
  ADMOB_NATIVE_AD_UNIT_IOS: ADMOB_NATIVE_AD_UNIT_IOS ?? '',
  ADMOB_NATIVE_AD_UNIT_ANDROID: ADMOB_NATIVE_AD_UNIT_ANDROID ?? '',
  // @feature:admob:end
  FACEBOOK_APP_ID: FACEBOOK_APP_ID ?? '',
  FACEBOOK_CLIENT_TOKEN: FACEBOOK_CLIENT_TOKEN ?? '',
  // @feature:adjust:start
  ADJUST_APP_TOKEN_ANDROID: ADJUST_APP_TOKEN_ANDROID ?? '',
  ADJUST_APP_TOKEN_IOS: ADJUST_APP_TOKEN_IOS ?? '',
  // @feature:adjust:end
  USER_CENTRIC: USER_CENTRIC ?? '',
  USER_CENTRIC_RULESET_ID: USER_CENTRIC_RULESET_ID ?? '',
  USER_CENTRIC_SETTINGS_ID: USER_CENTRIC_SETTINGS_ID ?? '',
  USER_CENTRIC_IDENTITY_MODE: USER_CENTRIC_IDENTITY_MODE ?? 'auto',
}
export default env
