import {
  SENTRY_DSN,
  SENTRY_URL,
  SENTRY_ORG,
  SENTRY_PROJECT,
  SENTRY_AUTH_TOKEN,
  FIREBASE_API_KEY,
  FIREBASE_APP_ID,
  FIREBASE_PROJECT_ID,
  REVENUECAT_IOS_KEY,
  REVENUECAT_ANDROID_KEY,
  APPLOVIN_SDK_KEY,
  APPLOVIN_BANNER_AD_UNIT_IOS,
  APPLOVIN_BANNER_AD_UNIT_ANDROID,
  APPLOVIN_INTERSTITIAL_AD_UNIT_IOS,
  APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID,
  APPLOVIN_REWARDED_AD_UNIT_IOS,
  APPLOVIN_REWARDED_AD_UNIT_ANDROID,
  APPLOVIN_APP_OPEN_AD_UNIT_IOS,
  APPLOVIN_APP_OPEN_AD_UNIT_ANDROID,
  FACEBOOK_APP_ID,
  FACEBOOK_CLIENT_TOKEN,
  APPSFLYER_DEV_KEY,
  APPSFLYER_APP_ID,
  USER_CENTRIC,
  ADMOB_APP_ID_IOS,
  ADMOB_APP_ID_ANDROID,
  IRONSOURCE_APP_KEY_IOS,
  IRONSOURCE_APP_KEY_ANDROID,
} from '@env'

export type Env = {
  FACEBOOK_DISPLAY_NAME: any
  SENTRY_DSN: string
  SENTRY_URL: string
  SENTRY_ORG: string
  SENTRY_PROJECT: string
  SENTRY_AUTH_TOKEN: string
  FIREBASE_API_KEY: string
  FIREBASE_APP_ID: string
  FIREBASE_PROJECT_ID: string
  REVENUECAT_IOS_KEY: string
  REVENUECAT_ANDROID_KEY: string
  APPLOVIN_SDK_KEY: string
  APPLOVIN_BANNER_AD_UNIT_IOS: string
  APPLOVIN_BANNER_AD_UNIT_ANDROID: string
  APPLOVIN_INTERSTITIAL_AD_UNIT_IOS: string
  APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID: string
  APPLOVIN_REWARDED_AD_UNIT_IOS: string
  APPLOVIN_REWARDED_AD_UNIT_ANDROID: string
  APPLOVIN_APP_OPEN_AD_UNIT_IOS: string
  APPLOVIN_APP_OPEN_AD_UNIT_ANDROID: string
  FACEBOOK_APP_ID: string
  FACEBOOK_CLIENT_TOKEN: string
  APPSFLYER_DEV_KEY: string
  APPSFLYER_APP_ID: string
  USER_CENTRIC: string
  ADMOB_APP_ID_IOS: string
  ADMOB_APP_ID_ANDROID: string
  IRONSOURCE_APP_KEY_IOS: string
  IRONSOURCE_APP_KEY_ANDROID: string
}

const env: Env = {
  FACEBOOK_DISPLAY_NAME: '',
  SENTRY_DSN: SENTRY_DSN ?? '',
  SENTRY_URL: SENTRY_URL ?? 'https://sentry.io/',
  SENTRY_ORG: SENTRY_ORG ?? '',
  SENTRY_PROJECT: SENTRY_PROJECT ?? '',
  SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN ?? '',
  FIREBASE_API_KEY: FIREBASE_API_KEY ?? '',
  FIREBASE_APP_ID: FIREBASE_APP_ID ?? '',
  FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID ?? '',
  REVENUECAT_IOS_KEY: REVENUECAT_IOS_KEY ?? '',
  REVENUECAT_ANDROID_KEY: REVENUECAT_ANDROID_KEY ?? '',
  APPLOVIN_SDK_KEY: APPLOVIN_SDK_KEY ?? '',
  APPLOVIN_BANNER_AD_UNIT_IOS: APPLOVIN_BANNER_AD_UNIT_IOS ?? '',
  APPLOVIN_BANNER_AD_UNIT_ANDROID: APPLOVIN_BANNER_AD_UNIT_ANDROID ?? '',
  APPLOVIN_INTERSTITIAL_AD_UNIT_IOS: APPLOVIN_INTERSTITIAL_AD_UNIT_IOS ?? '',
  APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID: APPLOVIN_INTERSTITIAL_AD_UNIT_ANDROID ?? '',
  APPLOVIN_REWARDED_AD_UNIT_IOS: APPLOVIN_REWARDED_AD_UNIT_IOS ?? '',
  APPLOVIN_REWARDED_AD_UNIT_ANDROID: APPLOVIN_REWARDED_AD_UNIT_ANDROID ?? '',
  APPLOVIN_APP_OPEN_AD_UNIT_IOS: APPLOVIN_APP_OPEN_AD_UNIT_IOS ?? '',
  APPLOVIN_APP_OPEN_AD_UNIT_ANDROID: APPLOVIN_APP_OPEN_AD_UNIT_ANDROID ?? '',
  FACEBOOK_APP_ID: FACEBOOK_APP_ID ?? '',
  FACEBOOK_CLIENT_TOKEN: FACEBOOK_CLIENT_TOKEN ?? '',
  APPSFLYER_DEV_KEY: APPSFLYER_DEV_KEY ?? '',
  APPSFLYER_APP_ID: APPSFLYER_APP_ID ?? '',
  USER_CENTRIC: USER_CENTRIC ?? '',
  ADMOB_APP_ID_IOS: ADMOB_APP_ID_IOS ?? '',
  ADMOB_APP_ID_ANDROID: ADMOB_APP_ID_ANDROID ?? '',
  IRONSOURCE_APP_KEY_IOS: IRONSOURCE_APP_KEY_IOS ?? '',
  IRONSOURCE_APP_KEY_ANDROID: IRONSOURCE_APP_KEY_ANDROID ?? '',
}
export default env
